# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

--- 
  trigger:
    - main

  resources:
    repositories: 
      - repository: templaterepo
        name: ADOtemplates
        ref: main
        type: git

  stages:
    - stage: buildstage
      displayName: build stages    
      jobs:
        - job: dotnetbuild
          displayName: "Build code"
          pool : default
          steps:
            - bash: "echo staging directory $(Build.ArtifactStagingDirectory) and number $(Build.BuildNumber)"
            - bash: env
            - task: DotNetCoreCLI@2
              displayName: 'build code'
              inputs:
                command: build
                projects: src/NopCommerce.sln
                configuration: Release
            - task: DotNetCoreCLI@2
              displayName: publish the project
              inputs:
                command: publish
                projects: src/Presentation/Nop.Web/Nop.Web.csproj
                zipAfterPublish: true
                configuration: Release
                arguments: "-o $(Build.ArtifactStagingDirectory)/Published"
            - task: PublishBuildArtifacts@1
              displayName: Make artifacts available
              inputs:
                PathtoPublish: $(Build.ArtifactStagingDirectory)/Published/Nop.Web.zip
                ArtifactName: 'nopCommerce'
                publishLocation: Container

    - stage: dockerstage
      displayName: Docker stage
      jobs:
        - job: dockerbuild
          displayName: "Build docker code and save in docker" 
          pool:
            name: "Azure Pipelines"
            vmImage: "ubuntu-20.04"
          steps:
            - template: DockerTemplate/docker-template.yaml@templaterepo



    




